spring:
  application:
    name: ${APPLICATION_NAME:SpringBootAuth}
  profiles:
    active: dev
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
  jackson:
    deserialization:
      fail-on-unknown-properties: true

app:
  host: http://localhost:8080
  security:
    jwt:
      private-key: classpath:keys/private.pem
      public-key: classpath:keys/public.pem
      expiration: ${JWT_EXPIRATION:86400000}
    cookie:
      name: access_token
      max-age: 86400
      secure: true
      http-only: true
      same-site: Strict
      path: /