spring:
  datasource:
    url: jdbc:h2:mem:h2-database
  driverClassName: org.h2.Driver
  username: sa
  password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: false