spring:
  datasource:
    url: ${DATABASE_HOST:jdbc:postgresql://localhost:5432/spring_auth_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
server:
  port: ${APPLICATION_PORT:8080}